import { CorelObject, CorelPage, ProjectDocument } from '../types/coreldraw';
import { rectToSubpaths, ellipseToSubpaths, starToSubpaths, polygonToSubpaths } from './vectorMath';

export interface TemplateDefinition {
  id: string;
  title: string;
  category: 'Branding' | 'Illustration' | 'Layout' | 'Infographics' | 'Badges';
  description: string;
  thumbnail: string; // SVG or color badge
  page: CorelPage;
  objects: CorelObject[];
}

export const PRESET_TEMPLATES: TemplateDefinition[] = [
  {
    id: 'corel-classic-balloon',
    title: 'Iconic Corel Balloon Logo',
    category: 'Branding',
    description: 'The legendary Corel hot-air balloon vector illustration with gradient segments, highlight gloss, and 3D typography.',
    thumbnail: '🎈',
    page: {
      id: 'p1',
      name: 'Page 1',
      width: 1000,
      height: 750,
      unit: 'px',
      preset: 'Standard',
      orientation: 'landscape',
      background: '#111827',
    },
    objects: [
      // Outer Glow / Backdrop
      {
        id: 'bg_glow',
        name: 'Backdrop Aura',
        type: 'ellipse',
        transform: { x: 300, y: 150, width: 400, height: 400, rotation: 0, scaleX: 1, scaleY: 1, skewX: 0, skewY: 0 },
        subpaths: ellipseToSubpaths(400, 400),
        fill: {
          type: 'radial',
          color: '#3b82f6',
          gradient: {
            type: 'radial',
            start: { x: 200, y: 200 },
            end: { x: 200, y: 0 },
            stops: [
              { offset: 0, color: 'rgba(59, 130, 246, 0.25)' },
              { offset: 1, color: 'rgba(17, 24, 39, 0)' },
            ],
          },
        },
        outline: { color: 'none', width: 0, style: 'solid', cap: 'round', join: 'round', startArrow: 'none', endArrow: 'none' },
        shadow: { enabled: false, color: '#000', blur: 0, offsetX: 0, offsetY: 0, opacity: 0 },
        extrude: { enabled: false, depth: 0, angle: 0, vanishingPoint: { x: 0, y: 0 }, bevel: 0, lightIntensity: 0.8 },
        contour: { enabled: false, type: 'outside', steps: 1, offset: 5, endColor: '#fff' },
        transparency: { enabled: false, type: 'uniform', opacity: 1 },
        opacity: 1,
        locked: true,
        visible: true,
        zIndex: 0,
      },
      // Left Green Balloon Stripe
      {
        id: 'balloon_stripe_green',
        name: 'Balloon Stripe (Emerald)',
        type: 'path',
        transform: { x: 380, y: 160, width: 90, height: 260, rotation: 0, scaleX: 1, scaleY: 1, skewX: 0, skewY: 0 },
        subpaths: [
          {
            isClosed: true,
            nodes: [
              { id: '1', x: 80, y: 0, handleOut: { x: 10, y: 40 }, type: 'smooth' },
              { id: '2', x: 0, y: 120, handleIn: { x: 0, y: 60 }, handleOut: { x: 0, y: 180 }, type: 'smooth' },
              { id: '3', x: 50, y: 250, handleIn: { x: 20, y: 220 }, type: 'smooth' },
              { id: '4', x: 75, y: 250, type: 'cusp' },
              { id: '5', x: 85, y: 0, type: 'cusp' },
            ],
          },
        ],
        fill: {
          type: 'linear',
          color: '#10b981',
          gradient: {
            type: 'linear',
            start: { x: 0, y: 0 },
            end: { x: 90, y: 260 },
            stops: [
              { offset: 0, color: '#34d399' },
              { offset: 1, color: '#059669' },
            ],
          },
        },
        outline: { color: '#064e3b', width: 2, style: 'solid', cap: 'round', join: 'round', startArrow: 'none', endArrow: 'none' },
        shadow: { enabled: true, color: '#000000', blur: 12, offsetX: 4, offsetY: 8, opacity: 0.4 },
        extrude: { enabled: false, depth: 0, angle: 0, vanishingPoint: { x: 0, y: 0 }, bevel: 0, lightIntensity: 0.8 },
        contour: { enabled: false, type: 'outside', steps: 1, offset: 5, endColor: '#fff' },
        transparency: { enabled: false, type: 'uniform', opacity: 1 },
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 1,
      },
      // Center Cyan Balloon Stripe
      {
        id: 'balloon_stripe_cyan',
        name: 'Balloon Stripe (Cyan)',
        type: 'path',
        transform: { x: 460, y: 155, width: 80, height: 265, rotation: 0, scaleX: 1, scaleY: 1, skewX: 0, skewY: 0 },
        subpaths: [
          {
            isClosed: true,
            nodes: [
              { id: '1', x: 5, y: 5, handleOut: { x: 40, y: 0 }, type: 'smooth' },
              { id: '2', x: 75, y: 5, handleIn: { x: 60, y: 0 }, type: 'smooth' },
              { id: '3', x: 55, y: 255, type: 'cusp' },
              { id: '4', x: 25, y: 255, type: 'cusp' },
            ],
          },
        ],
        fill: {
          type: 'linear',
          color: '#06b6d4',
          gradient: {
            type: 'linear',
            start: { x: 0, y: 0 },
            end: { x: 80, y: 265 },
            stops: [
              { offset: 0, color: '#38bdf8' },
              { offset: 1, color: '#0284c7' },
            ],
          },
        },
        outline: { color: '#0369a1', width: 2, style: 'solid', cap: 'round', join: 'round', startArrow: 'none', endArrow: 'none' },
        shadow: { enabled: true, color: '#000000', blur: 10, offsetX: 2, offsetY: 6, opacity: 0.3 },
        extrude: { enabled: false, depth: 0, angle: 0, vanishingPoint: { x: 0, y: 0 }, bevel: 0, lightIntensity: 0.8 },
        contour: { enabled: false, type: 'outside', steps: 1, offset: 5, endColor: '#fff' },
        transparency: { enabled: false, type: 'uniform', opacity: 1 },
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 2,
      },
      // Right Magenta Balloon Stripe
      {
        id: 'balloon_stripe_magenta',
        name: 'Balloon Stripe (Magenta)',
        type: 'path',
        transform: { x: 530, y: 160, width: 90, height: 260, rotation: 0, scaleX: 1, scaleY: 1, skewX: 0, skewY: 0 },
        subpaths: [
          {
            isClosed: true,
            nodes: [
              { id: '1', x: 5, y: 0, type: 'cusp' },
              { id: '2', x: 15, y: 0, handleOut: { x: 75, y: 40 }, type: 'smooth' },
              { id: '3', x: 90, y: 120, handleIn: { x: 90, y: 60 }, handleOut: { x: 90, y: 180 }, type: 'smooth' },
              { id: '4', x: 40, y: 250, handleIn: { x: 70, y: 220 }, type: 'smooth' },
              { id: '5', x: 15, y: 250, type: 'cusp' },
            ],
          },
        ],
        fill: {
          type: 'linear',
          color: '#ec4899',
          gradient: {
            type: 'linear',
            start: { x: 0, y: 0 },
            end: { x: 90, y: 260 },
            stops: [
              { offset: 0, color: '#f472b6' },
              { offset: 1, color: '#be185d' },
            ],
          },
        },
        outline: { color: '#831843', width: 2, style: 'solid', cap: 'round', join: 'round', startArrow: 'none', endArrow: 'none' },
        shadow: { enabled: true, color: '#000000', blur: 12, offsetX: 4, offsetY: 8, opacity: 0.4 },
        extrude: { enabled: false, depth: 0, angle: 0, vanishingPoint: { x: 0, y: 0 }, bevel: 0, lightIntensity: 0.8 },
        contour: { enabled: false, type: 'outside', steps: 1, offset: 5, endColor: '#fff' },
        transparency: { enabled: false, type: 'uniform', opacity: 1 },
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 3,
      },
      // Balloon Basket
      {
        id: 'balloon_basket',
        name: 'Woven Basket',
        type: 'rect',
        transform: { x: 475, y: 440, width: 50, height: 35, rotation: 0, scaleX: 1, scaleY: 1, skewX: 0, skewY: 0 },
        rectProps: { cornerRadii: [4, 4, 8, 8], isRoundedLinked: true },
        subpaths: rectToSubpaths(50, 35, [4, 4, 8, 8]),
        fill: { type: 'solid', color: '#b45309' },
        outline: { color: '#78350f', width: 2, style: 'solid', cap: 'round', join: 'round', startArrow: 'none', endArrow: 'none' },
        shadow: { enabled: true, color: '#000000', blur: 6, offsetX: 0, offsetY: 4, opacity: 0.5 },
        extrude: { enabled: true, depth: 8, angle: 45, vanishingPoint: { x: 0, y: 0 }, bevel: 0, lightIntensity: 0.9, sideColor: '#78350f' },
        contour: { enabled: false, type: 'outside', steps: 1, offset: 5, endColor: '#fff' },
        transparency: { enabled: false, type: 'uniform', opacity: 1 },
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 4,
      },
      // Main CorelDRAW Title with 3D Extrusion
      {
        id: 'corel_title',
        name: 'CorelDRAW Heading',
        type: 'text',
        transform: { x: 500, y: 560, width: 600, height: 80, rotation: 0, scaleX: 1, scaleY: 1, skewX: 0, skewY: 0 },
        subpaths: [],
        textProps: {
          text: 'CorelDRAW',
          fontFamily: 'Outfit, Montserrat, sans-serif',
          fontSize: 64,
          fontWeight: 800,
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          letterSpacing: 2,
          lineHeight: 1.1,
        },
        fill: {
          type: 'linear',
          color: '#ffffff',
          gradient: {
            type: 'linear',
            start: { x: 0, y: 0 },
            end: { x: 0, y: 80 },
            stops: [
              { offset: 0, color: '#ffffff' },
              { offset: 1, color: '#94a3b8' },
            ],
          },
        },
        outline: { color: '#00e676', width: 2, style: 'solid', cap: 'round', join: 'round', startArrow: 'none', endArrow: 'none' },
        shadow: { enabled: true, color: '#000000', blur: 16, offsetX: 4, offsetY: 10, opacity: 0.6 },
        extrude: { enabled: true, depth: 12, angle: 45, vanishingPoint: { x: 0, y: 0 }, bevel: 0, lightIntensity: 0.8, sideColor: '#0f766e' },
        contour: { enabled: false, type: 'outside', steps: 1, offset: 5, endColor: '#fff' },
        transparency: { enabled: false, type: 'uniform', opacity: 1 },
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 5,
      },
      // Subtitle
      {
        id: 'corel_subtitle',
        name: 'Vector Graphics Suite Subtitle',
        type: 'text',
        transform: { x: 500, y: 640, width: 600, height: 30, rotation: 0, scaleX: 1, scaleY: 1, skewX: 0, skewY: 0 },
        subpaths: [],
        textProps: {
          text: 'VECTOR GRAPHICS & ILLUSTRATION STUDIO',
          fontFamily: 'Inter, sans-serif',
          fontSize: 16,
          fontWeight: 600,
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          letterSpacing: 6,
          lineHeight: 1,
        },
        fill: { type: 'solid', color: '#38bdf8' },
        outline: { color: 'none', width: 0, style: 'solid', cap: 'round', join: 'round', startArrow: 'none', endArrow: 'none' },
        shadow: { enabled: false, color: '#000', blur: 0, offsetX: 0, offsetY: 0, opacity: 0 },
        extrude: { enabled: false, depth: 0, angle: 0, vanishingPoint: { x: 0, y: 0 }, bevel: 0, lightIntensity: 0.8 },
        contour: { enabled: false, type: 'outside', steps: 1, offset: 5, endColor: '#fff' },
        transparency: { enabled: false, type: 'uniform', opacity: 1 },
        opacity: 0.9,
        locked: false,
        visible: true,
        zIndex: 6,
      },
    ],
  },
  {
    id: 'cyberpunk-badge',
    title: 'Cyberpunk Vector Emblem',
    category: 'Illustration',
    description: 'Futuristic geometric badge featuring star polygons, high-contrast neon gradients, contour offsets, and angular precision lines.',
    thumbnail: '⚡',
    page: {
      id: 'p2',
      name: 'Cyberpunk Emblem',
      width: 800,
      height: 800,
      unit: 'px',
      preset: 'Square',
      orientation: 'landscape',
      background: '#090d16',
    },
    objects: [
      // Outer Hexagon
      {
        id: 'cyber_hex',
        name: 'Shield Hexagon',
        type: 'polygon',
        transform: { x: 200, y: 150, width: 400, height: 400, rotation: 0, scaleX: 1, scaleY: 1, skewX: 0, skewY: 0 },
        polygonProps: { sides: 6 },
        subpaths: polygonToSubpaths(400, 400, 6),
        fill: {
          type: 'linear',
          color: '#1e1b4b',
          gradient: {
            type: 'linear',
            start: { x: 0, y: 0 },
            end: { x: 400, y: 400 },
            stops: [
              { offset: 0, color: '#312e81' },
              { offset: 1, color: '#0f172a' },
            ],
          },
        },
        outline: { color: '#06b6d4', width: 4, style: 'solid', cap: 'round', join: 'round', startArrow: 'none', endArrow: 'none' },
        shadow: { enabled: true, color: '#06b6d4', blur: 25, offsetX: 0, offsetY: 0, opacity: 0.5 },
        extrude: { enabled: true, depth: 15, angle: 45, vanishingPoint: { x: 0, y: 0 }, bevel: 0, lightIntensity: 0.85, sideColor: '#1e1b4b' },
        contour: { enabled: true, type: 'inside', steps: 2, offset: 12, endColor: '#ec4899' },
        transparency: { enabled: false, type: 'uniform', opacity: 1 },
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 1,
      },
      // Inner Neon Star
      {
        id: 'cyber_star',
        name: 'Core Star Matrix',
        type: 'star',
        transform: { x: 275, y: 225, width: 250, height: 250, rotation: 0, scaleX: 1, scaleY: 1, skewX: 0, skewY: 0 },
        starProps: { points: 8, sharpness: 0.65 },
        subpaths: starToSubpaths(250, 250, 8, 0.65),
        fill: {
          type: 'linear',
          color: '#ec4899',
          gradient: {
            type: 'linear',
            start: { x: 0, y: 0 },
            end: { x: 250, y: 250 },
            stops: [
              { offset: 0, color: '#f43f5e' },
              { offset: 1, color: '#8b5cf6' },
            ],
          },
        },
        outline: { color: '#fbcfe8', width: 2, style: 'solid', cap: 'round', join: 'round', startArrow: 'none', endArrow: 'none' },
        shadow: { enabled: true, color: '#f43f5e', blur: 20, offsetX: 0, offsetY: 0, opacity: 0.6 },
        extrude: { enabled: false, depth: 0, angle: 0, vanishingPoint: { x: 0, y: 0 }, bevel: 0, lightIntensity: 0.8 },
        contour: { enabled: false, type: 'outside', steps: 1, offset: 5, endColor: '#fff' },
        transparency: { enabled: false, type: 'uniform', opacity: 1 },
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 2,
      },
      // Emblem Text
      {
        id: 'cyber_text',
        name: 'Emblem Typography',
        type: 'text',
        transform: { x: 400, y: 620, width: 500, height: 50, rotation: 0, scaleX: 1, scaleY: 1, skewX: 0, skewY: 0 },
        subpaths: [],
        textProps: {
          text: 'V E C T O R  N E X U S',
          fontFamily: 'Space Grotesk, sans-serif',
          fontSize: 32,
          fontWeight: 700,
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'center',
          letterSpacing: 4,
          lineHeight: 1,
        },
        fill: { type: 'solid', color: '#22d3ee' },
        outline: { color: 'none', width: 0, style: 'solid', cap: 'round', join: 'round', startArrow: 'none', endArrow: 'none' },
        shadow: { enabled: true, color: '#06b6d4', blur: 15, offsetX: 0, offsetY: 0, opacity: 0.7 },
        extrude: { enabled: false, depth: 0, angle: 0, vanishingPoint: { x: 0, y: 0 }, bevel: 0, lightIntensity: 0.8 },
        contour: { enabled: false, type: 'outside', steps: 1, offset: 5, endColor: '#fff' },
        transparency: { enabled: false, type: 'uniform', opacity: 1 },
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 3,
      },
    ],
  },
  {
    id: 'business-stationery',
    title: 'Brand Stationery & Business Card',
    category: 'Layout',
    description: 'Clean print-ready layout with dimension lines, color swatches, contact grid, and vector logo marks.',
    thumbnail: '💼',
    page: {
      id: 'p3',
      name: 'Business Card Layout',
      width: 1050,
      height: 600,
      unit: 'px',
      preset: 'Business Card',
      orientation: 'landscape',
      background: '#f8fafc',
    },
    objects: [
      // Left Brand Card Face
      {
        id: 'card_dark_side',
        name: 'Card Front (Dark)',
        type: 'rect',
        transform: { x: 80, y: 100, width: 400, height: 240, rotation: 0, scaleX: 1, scaleY: 1, skewX: 0, skewY: 0 },
        rectProps: { cornerRadii: [12, 12, 12, 12], isRoundedLinked: true },
        subpaths: rectToSubpaths(400, 240, [12, 12, 12, 12]),
        fill: {
          type: 'linear',
          color: '#0f172a',
          gradient: {
            type: 'linear',
            start: { x: 0, y: 0 },
            end: { x: 400, y: 240 },
            stops: [
              { offset: 0, color: '#1e293b' },
              { offset: 1, color: '#0f172a' },
            ],
          },
        },
        outline: { color: '#334155', width: 1.5, style: 'solid', cap: 'round', join: 'round', startArrow: 'none', endArrow: 'none' },
        shadow: { enabled: true, color: '#000000', blur: 20, offsetX: 0, offsetY: 12, opacity: 0.15 },
        extrude: { enabled: false, depth: 0, angle: 0, vanishingPoint: { x: 0, y: 0 }, bevel: 0, lightIntensity: 0.8 },
        contour: { enabled: false, type: 'outside', steps: 1, offset: 5, endColor: '#fff' },
        transparency: { enabled: false, type: 'uniform', opacity: 1 },
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 1,
      },
      // Front Card Logo Mark
      {
        id: 'card_logo_poly',
        name: 'Brand Prism',
        type: 'polygon',
        transform: { x: 120, y: 150, width: 60, height: 60, rotation: 0, scaleX: 1, scaleY: 1, skewX: 0, skewY: 0 },
        polygonProps: { sides: 3 },
        subpaths: polygonToSubpaths(60, 60, 3),
        fill: { type: 'solid', color: '#10b981' },
        outline: { color: 'none', width: 0, style: 'solid', cap: 'round', join: 'round', startArrow: 'none', endArrow: 'none' },
        shadow: { enabled: false, color: '#000', blur: 0, offsetX: 0, offsetY: 0, opacity: 0 },
        extrude: { enabled: false, depth: 0, angle: 0, vanishingPoint: { x: 0, y: 0 }, bevel: 0, lightIntensity: 0.8 },
        contour: { enabled: false, type: 'outside', steps: 1, offset: 5, endColor: '#fff' },
        transparency: { enabled: false, type: 'uniform', opacity: 1 },
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 2,
      },
      // Front Card Name
      {
        id: 'card_text_name',
        name: 'Brand Typography',
        type: 'text',
        transform: { x: 200, y: 165, width: 250, height: 40, rotation: 0, scaleX: 1, scaleY: 1, skewX: 0, skewY: 0 },
        subpaths: [],
        textProps: {
          text: 'NEXUS STUDIOS',
          fontFamily: 'Montserrat, sans-serif',
          fontSize: 20,
          fontWeight: 700,
          fontStyle: 'normal',
          textDecoration: 'none',
          textAlign: 'left',
          letterSpacing: 2,
          lineHeight: 1,
        },
        fill: { type: 'solid', color: '#ffffff' },
        outline: { color: 'none', width: 0, style: 'solid', cap: 'round', join: 'round', startArrow: 'none', endArrow: 'none' },
        shadow: { enabled: false, color: '#000', blur: 0, offsetX: 0, offsetY: 0, opacity: 0 },
        extrude: { enabled: false, depth: 0, angle: 0, vanishingPoint: { x: 0, y: 0 }, bevel: 0, lightIntensity: 0.8 },
        contour: { enabled: false, type: 'outside', steps: 1, offset: 5, endColor: '#fff' },
        transparency: { enabled: false, type: 'uniform', opacity: 1 },
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 3,
      },
      // Right Card Face (Light)
      {
        id: 'card_light_side',
        name: 'Card Back (Light)',
        type: 'rect',
        transform: { x: 550, y: 100, width: 400, height: 240, rotation: 0, scaleX: 1, scaleY: 1, skewX: 0, skewY: 0 },
        rectProps: { cornerRadii: [12, 12, 12, 12], isRoundedLinked: true },
        subpaths: rectToSubpaths(400, 240, [12, 12, 12, 12]),
        fill: { type: 'solid', color: '#ffffff' },
        outline: { color: '#e2e8f0', width: 1.5, style: 'solid', cap: 'round', join: 'round', startArrow: 'none', endArrow: 'none' },
        shadow: { enabled: true, color: '#000000', blur: 20, offsetX: 0, offsetY: 12, opacity: 0.08 },
        extrude: { enabled: false, depth: 0, angle: 0, vanishingPoint: { x: 0, y: 0 }, bevel: 0, lightIntensity: 0.8 },
        contour: { enabled: false, type: 'outside', steps: 1, offset: 5, endColor: '#fff' },
        transparency: { enabled: false, type: 'uniform', opacity: 1 },
        opacity: 1,
        locked: false,
        visible: true,
        zIndex: 4,
      },
      // Dimension line demonstration
      {
        id: 'card_dimension',
        name: 'Width Dimension Guide',
        type: 'dimension',
        transform: { x: 80, y: 370, width: 400, height: 30, rotation: 0, scaleX: 1, scaleY: 1, skewX: 0, skewY: 0 },
        subpaths: [],
        dimensionProps: {
          start: { x: 80, y: 360 },
          end: { x: 480, y: 360 },
          offset: 20,
          unit: 'mm',
          decimalPlaces: 1,
          showUnits: true,
        },
        fill: { type: 'none', color: '#64748b' },
        outline: { color: '#64748b', width: 1.5, style: 'solid', cap: 'round', join: 'round', startArrow: 'arrow', endArrow: 'arrow' },
        shadow: { enabled: false, color: '#000', blur: 0, offsetX: 0, offsetY: 0, opacity: 0 },
        extrude: { enabled: false, depth: 0, angle: 0, vanishingPoint: { x: 0, y: 0 }, bevel: 0, lightIntensity: 0.8 },
        contour: { enabled: false, type: 'outside', steps: 1, offset: 5, endColor: '#fff' },
        transparency: { enabled: false, type: 'uniform', opacity: 1 },
        opacity: 1,
        locked: true,
        visible: true,
        zIndex: 5,
      },
    ],
  },
];
